/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class HtmlHeading {
  level: number
  text?: string
  id?: string
  constructor(level: number, text?: string, id?: string)
}
export type HTMLHeading = HtmlHeading

export declare export declare function extractHeadingsFromHtml(html: string): Array<HtmlHeading>
