/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function extractHeadingsFromHtml(html: string): Array<HtmlHeading>
export type HTMLHeading = HtmlHeading
export declare class HtmlHeading {
  level: number
  text?: string
  id?: string
  constructor(level: number, text?: string, id?: string)
}
